package com.sakethh.linkora.common.utils

enum class LinkoraExports {
    SAVED_LINKS__LINKORA_EXPORT,
    IMPORTANT_LINKS__LINKORA_EXPORT,
    REGULAR_FOLDERS__LINKORA_EXPORT,
    HISTORY_LINKS__LINKORA_EXPORT,
    ARCHIVED_LINKS__LINKORA_EXPORT,
    ARCHIVED_FOLDERS__LINKORA_EXPORT,
}