package com.sakethh.linkora.common.preferences

enum class AppPreferenceType {
    DARK_THEME, AMOLED_THEME_STATE, DYNAMIC_THEMING, JSOUP_USER_AGENT, SECONDARY_JSOUP_USER_AGENT, FOLLOW_SYSTEM_THEME, SETTING_COMPONENT_DESCRIPTION_STATE,
    CUSTOM_TABS, AUTO_DETECT_TITLE_FOR_LINK, AUTO_CHECK_UPDATES, HOME_SCREEN_VISIBILITY, SORTING_PREFERENCE,
    SEND_CRASH_REPORTS, IS_DATA_MIGRATION_COMPLETED_FROM_V9, CURRENT_WORK_MANAGER_WORK_UUID, SHELF_VISIBLE_STATE, LAST_SELECTED_PANEL_ID, APP_LANGUAGE_NAME,
    APP_LANGUAGE_CODE, USE_REMOTE_LANGUAGE_STRINGS, TOTAL_REMOTE_STRINGS, REMOTE_STRINGS_LAST_UPDATED_ON, LOCALIZATION_SERVER_URL,
    ASSOCIATED_IMAGES_IN_LINK_MENU_VISIBILITY, CURRENTLY_SELECTED_LINK_VIEW, BORDER_VISIBILITY_FOR_NON_LIST_VIEWS,
    TITLE_VISIBILITY_FOR_NON_LIST_VIEWS, BASE_URL_VISIBILITY_FOR_NON_LIST_VIEWS, FADED_EDGE_VISIBILITY_FOR_NON_LIST_VIEWS,
    FORCE_SAVE_WITHOUT_FETCHING_META_DATA, INITIAL_ROUTE, SERVER_URL, SERVER_SYNC_TYPE, SERVER_AUTH_TOKEN, DESKTOP_TOP_DECORATOR, LAST_REFRESHED_LINK_INDEX,
    SERVER_CORRELATION, LAST_TIME_SYNCED_WITH_SERVER, SHOW_VIDEO_TAG_IF_APPLICABLE, SHOULD_SHOW_ONBOARDING, FORCE_SHUFFLE_LINKS, NOTE_VISIBILITY_IN_LIST_VIEWS
}